# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c75e4fc13e2a9b1cf4c869236670e7f45cbb32c926c58440f578414f7fb7c00c6bfa940caca7b543d2f2d3f6280a4a2fa3ef02856a0ea9252191c3f207dffa4

test:
  secret_key_base: 1624c3f7d79b5b58094baf21635c6eba1a8c8d83aeb257f8ad92a51fb3d4b004cdca29c14175edd1c7d4066147da6a8dc087549eac304364e59b24d6286343d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
